server:
  port: 9901

  servlet:
    context-path: /information
spring:
  profiles:
    active: dev
  jackson:
    default-property-inclusion: non_null
  application:
    name: CHAOSHAN-INFORMATION
  main:
    allow-bean-definition-overriding: true

token:
  jwt:
    signature-key: chaoshan
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  
feign:
  client:
    config:
      default:
        #不设置connectTimeout会导致readTimeout设置不生效
        connectTimeout: 3000
        readTimeout: 6000