server:
  port: 8000

spring:
  application:
    name: GATEWAY
  #     配置最大文件大小
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB
  profiles:
    active: dev
  #  cloud:
  #    nacos:
  #      discovery:
  #        server-addr: 192.168.137.7:8848
  #        namespace: 5316272c-6a95-4a4e-836c-fbc8f9c3b5e4

  main:
    allow-bean-definition-overriding: true


token:
  jwt:
    signature-key: chaoshan
zuul:
  host:
    connect-timeout-millis: 15000 #HTTP连接超时大于流量控制的超时时间
    socket-timeout-millis: 60000   #socket超时
  routes:
    CHAOSHAN-AUTH:
      stripPrefix: false
      path: /auth/**
    #    demo:
    #     stripPrefix: false
    #     path: /demo/**
    CHAOSHAN-USER:
      stripPrefix: false
      path: /user/**
    CHAOSHAN-ARTICLE:
      stripPrefix: false
      path: /article/**
    CHAOSHAN-INFORMATION:
      stripPrefix: false
      path: /information/**
    CHAOSHAN-TODAY:
      stripPrefix: false
      path: /today/**

  retryable: true
  ignored-services: "*"
  sensitive-headers: "*"
  add-host-header: true
ribbon: #设置ribbon的超时时间小于zuul的超时时间
  ReadTimeout: 10000
  ConnectTimeout: 10000

swagger:
  servers:
    #    - {name: demo,location: /demo/v2/api-docs, version: 2.0}
    #    - {name: auth,location: /auth/v2/api-docs, version: 2.0}
    - { name: user,location: /user/v2/api-docs, version: 2.0 }
    - { name: article,location: /article/v2/api-docs, version: 2.0 }
    - { name: information,location: /information/v2/api-docs, version: 2.0 }
    - { name: today,location: /today/v2/api-docs, version: 2.0 }

chaoshan:
  modules:
    #    - demo
    - user
    - article
    - information
    - today

