server:
  port: 8000

spring:
  application:
    name: GATEWAY
  #     配置最大文件大小
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB
  profiles:
    active: dev

  main:
    allow-bean-definition-overriding: true


token:
  jwt:
    signature-key: chaoshan
zuul:
  host:
    connect-timeout-millis: 15000 #HTTP连接超时大于流量控制的超时时间
    socket-timeout-millis: 60000   #socket超时
  routes:
    CHAOSHAN-AUTH:
      stripPrefix: false
      path: /auth/**
    CHAOSHAN-USER:
      stripPrefix: false
      path: /user/**
    CHAOSHAN-ARTICLE:
      stripPrefix: false
      path: /article/**
    CHAOSHAN-INFORMATION:
      stripPrefix: false
      path: /information/**
    CHAOSHAN-TODAY:
      stripPrefix: false
      path: /today/**

  retryable: true
  ignored-services: "*"
  sensitive-headers: "*"
  add-host-header: true
ribbon: #设置ribbon的超时时间小于zuul的超时时间
  ReadTimeout: 10000
  ConnectTimeout: 10000

swagger:
  servers:
    - { name: user,location: /user/v2/api-docs, version: 2.0 }
    - { name: article,location: /article/v2/api-docs, version: 2.0 }
    - { name: information,location: /information/v2/api-docs, version: 2.0 }
    - { name: today,location: /today/v2/api-docs, version: 2.0 }

chaoshan:
  modules:
    - user
    - article
    - information
    - today

