server:
  port: 9100

  servlet:
    context-path: /article
spring:
  profiles:
    active: dev
  application:
    name: CHAOSHAN-ARTICLE
  jackson:
    default-property-inclusion: non_null
    #  rabbitmq:
    #    host: 192.168.137.7
    #    port: 5672
    #    username: admin
    #    password: admin

    virtual-host: /
    listener:
      simple:
        prefetch: 1    # 工作队列能者多劳模式
  #  cloud:
  #    nacos:
  #      discovery:
  #        server-addr: 192.168.137.7:8848
  #        namespace: 5316272c-6a95-4a4e-836c-fbc8f9c3b5e4
  #  datasource:
  #    type: com.alibaba.druid.pool.DruidDataSource
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    username: root
  #    password: 83821979Zs
  #    url: jdbc:mysql://localhost:3306/chaoshan?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
  main:
    allow-bean-definition-overriding: true
#  redis:
#    host: 192.168.137.7

token:
  jwt:
    signature-key: chaoshan
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml

#elasticsearch:
#  host: 192.168.137.7:9200
feign:
  client:
    config:
      default:
        #不设置connectTimeout会导致readTimeout设置不生效
        connectTimeout: 3000
        readTimeout: 6000

