spring:
  cloud:
    nacos:
      discovery:
        server-addr: ...
  #        namespace: 5316272c-6a95-4a4e-836c-fbc8f9c3b5e4
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    # tjq
    url: jdbc:mysql:/...:3306/chaoshan?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2b8
  main:
    allow-bean-definition-overriding: true
  redis:
    host: ...
    port: 6379
    lettuce:
      pool:
        max-active: 8
        # 超时关闭时间
        max-wait: -1ms
        max-idle: 5
        min-idle: 0
      shutdown-timeout: 100
    timeout: 30000ms
    password: ...
  rabbitmq:
    host: ...
    port: 5672
    username: root
    password: root
    virtual-host: /
    listener:
      simple:
        prefetch: 1    # 工作队列能者多劳模式

elasticsearch:
  host: ...

#logging:
#  level:
#    root: OFF
#    com.chaoshan: info

