server:
  port: 9000
  servlet:
    context-path: /auth
spring:
  application:
    name: CHAOSHAN-AUTH
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true

token:
  jwt:
    signature-key: chaoshan
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
