spring:
  cloud:
    nacos:
      discovery:
        server-addr: ...
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ...
    password: ...
    # tjq
    url: jdbc:mysql://.../chaoshan?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
